/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.Administrador;

import java.awt.BorderLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import vista.Administrador.paneles.PanelConfiguracionAdm;
import vista.Administrador.paneles.PanelEmpleadoAdm;
import vista.Administrador.paneles.PanelHabitacionesAdm;
import vista.Administrador.paneles.PanelPerfilAdm;
import vista.Administrador.paneles.PanelRecervasAdm;
import vista.Administrador.paneles.PanelTipoHabitacionesAdm;
import vista.Administrador.paneles.PanelUsuariosAdm;

/**
 *
 * @author FranDev
 */
public class JfrmAdministradorPrueba extends javax.swing.JFrame {

    public PanelEmpleadoAdm panelEmpleadoAdm = new PanelEmpleadoAdm();
    public PanelHabitacionesAdm panelHabitacionesAdm = new PanelHabitacionesAdm();
    public PanelTipoHabitacionesAdm panelTipoHabitacionesAdm = new PanelTipoHabitacionesAdm();
    public PanelPerfilAdm panelPerfilAdm = new PanelPerfilAdm();
    public  PanelRecervasAdm panelRecervasAdm = new PanelRecervasAdm();

    /**
     * Creates new form JfrmAdministrador
     */
    public JfrmAdministradorPrueba() {
        initComponents();
        setVisible(false);

        //setAlwaysOnTop(true);
        /* ************ para pantalla grande **************
       GraphicsDevice dispositivoGrafico = GraphicsEnvironment
                .getLocalGraphicsEnvironment().getDefaultScreenDevice();

        dispositivoGrafico.setFullScreenWindow(this);  */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        bntEmpleado = new javax.swing.JButton();
        btnGestionHabi = new javax.swing.JButton();
        btnTipoHabitaciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnConfiguracion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelPaginas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        panelBotones.setBackground(new java.awt.Color(0, 0, 0));
        panelBotones.setForeground(new java.awt.Color(255, 204, 102));
        panelBotones.setLayout(new java.awt.GridLayout(0, 1, 0, 15));

        btnInicio.setText("Inicio");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelBotones.add(btnInicio);

        btnPerfil.setText("Perfil");
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        panelBotones.add(btnPerfil);

        bntEmpleado.setText("Empleados");
        bntEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntEmpleadoMouseClicked(evt);
            }
        });
        bntEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEmpleadoActionPerformed(evt);
            }
        });
        panelBotones.add(bntEmpleado);

        btnGestionHabi.setText("Habitaciones");
        btnGestionHabi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionHabiMouseClicked(evt);
            }
        });
        btnGestionHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionHabiActionPerformed(evt);
            }
        });
        panelBotones.add(btnGestionHabi);

        btnTipoHabitaciones.setText("Tipo Habitaciones");
        btnTipoHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoHabitacionesActionPerformed(evt);
            }
        });
        panelBotones.add(btnTipoHabitaciones);

        jButton1.setText("Reservas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBotones.add(jButton1);

        jToggleButton1.setText("Clientes");
        panelBotones.add(jToggleButton1);

        btnConfiguracion.setText("Configuracion");
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseClicked(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        panelBotones.add(btnConfiguracion);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\PROYECTOS UNI\\Proyectos-Desktop\\SystemHotelReservas\\src\\main\\java\\Imagenes\\icons8-usuario-96.png")); // NOI18N

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 750));

        panelPaginas.setBackground(new java.awt.Color(153, 255, 51));
        panelPaginas.setAutoscrolls(true);
        panelPaginas.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1210, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked

    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked

    }//GEN-LAST:event_btnPerfilMouseClicked

    private void bntEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEmpleadoMouseClicked

    }//GEN-LAST:event_bntEmpleadoMouseClicked

    private void btnGestionHabiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionHabiMouseClicked

    }//GEN-LAST:event_btnGestionHabiMouseClicked

    private void btnConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseClicked

    }//GEN-LAST:event_btnConfiguracionMouseClicked

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed

// Asegúrate de usar GridLayout con una sola celda (1 fila, 1 columna)
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelPerfilAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();


    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnGestionHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionHabiActionPerformed

// Asegúrate de usar GridLayout con una sola celda (1 fila, 1 columna)
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelHabitacionesAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnGestionHabiActionPerformed

    private void bntEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEmpleadoActionPerformed

// Asegúrate de usar GridLayout con una sola celda (1 fila, 1 columna)
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelEmpleadoAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();

    }//GEN-LAST:event_bntEmpleadoActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        PanelConfiguracionAdm configuracionAdm = new PanelConfiguracionAdm();

        this.panelPaginas.removeAll();
        this.panelPaginas.add(configuracionAdm);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnTipoHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoHabitacionesActionPerformed

        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelTipoHabitacionesAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnTipoHabitacionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.panelPaginas.removeAll();
        this.panelPaginas.add(panelRecervasAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmAdministradorPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntEmpleado;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnGestionHabi;
    private javax.swing.JButton btnInicio;
    public javax.swing.JButton btnPerfil;
    public javax.swing.JButton btnTipoHabitaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPaginas;
    // End of variables declaration//GEN-END:variables

}
