/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.Administrador;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import vista.Administrador.paneles.PanelClientesAdm;
import vista.Administrador.paneles.PanelConfiguracionAdm;
import vista.Administrador.paneles.PanelEmpleadoAdm;
import vista.Administrador.paneles.PanelHabitacionesAdm;
import vista.Administrador.paneles.PanelInicio;
import vista.Administrador.paneles.PanelPerfilAdm;
import vista.Administrador.paneles.PanelRecervasAdm;
import vista.Administrador.paneles.PanelTipoHabitacionesAdm;

/**
 *
 * @author FranDev
 */
public class JfrmAdministradorPrueba extends javax.swing.JFrame {

    public PanelEmpleadoAdm panelEmpleadoAdm = new PanelEmpleadoAdm();
    public PanelHabitacionesAdm panelHabitacionesAdm = new PanelHabitacionesAdm();
    public PanelTipoHabitacionesAdm panelTipoHabitacionesAdm = new PanelTipoHabitacionesAdm();
    public PanelPerfilAdm panelPerfilAdm = new PanelPerfilAdm();
    public PanelRecervasAdm panelRecervasAdm = new PanelRecervasAdm();

    public PanelInicio panelInicio = new PanelInicio();
    public PanelClientesAdm panelClientesAdm = new PanelClientesAdm();

    /**
     * Creates new form JfrmAdministrador
     */
    public JfrmAdministradorPrueba() {
        initComponents();
        setVisible(false);
        this.setLocationRelativeTo(null);
        //setAlwaysOnTop(true);
        /* ************ para pantalla grande **************
       GraphicsDevice dispositivoGrafico = GraphicsEnvironment
                .getLocalGraphicsEnvironment().getDefaultScreenDevice();

        dispositivoGrafico.setFullScreenWindow(this);  */
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelInicio);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();

        interacionBontenes(btnInicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        bntEmpleado = new javax.swing.JButton();
        btnGestionHabi = new javax.swing.JButton();
        btnTipoHabitaciones = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelPaginas = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setBackground(new java.awt.Color(51, 51, 51));
        panelBotones.setForeground(new java.awt.Color(255, 255, 255));
        panelBotones.setLayout(new java.awt.GridLayout(0, 1, 0, 15));

        btnInicio.setBackground(new java.awt.Color(204, 204, 204));
        btnInicio.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(51, 51, 51));
        btnInicio.setText("Inicio");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        btnInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInicioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnInicioKeyReleased(evt);
            }
        });
        panelBotones.add(btnInicio);

        btnPerfil.setBackground(new java.awt.Color(204, 204, 204));
        btnPerfil.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(51, 51, 51));
        btnPerfil.setText("Perfil");
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        panelBotones.add(btnPerfil);

        bntEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        bntEmpleado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        bntEmpleado.setText("Empleados");
        bntEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntEmpleadoMouseClicked(evt);
            }
        });
        bntEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEmpleadoActionPerformed(evt);
            }
        });
        panelBotones.add(bntEmpleado);

        btnGestionHabi.setBackground(new java.awt.Color(204, 204, 204));
        btnGestionHabi.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGestionHabi.setForeground(new java.awt.Color(51, 51, 51));
        btnGestionHabi.setText("Habitaciones");
        btnGestionHabi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionHabiMouseClicked(evt);
            }
        });
        btnGestionHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionHabiActionPerformed(evt);
            }
        });
        panelBotones.add(btnGestionHabi);

        btnTipoHabitaciones.setBackground(new java.awt.Color(204, 204, 204));
        btnTipoHabitaciones.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnTipoHabitaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnTipoHabitaciones.setText("Tipo Habitaciones");
        btnTipoHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTipoHabitacionesMouseClicked(evt);
            }
        });
        btnTipoHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoHabitacionesActionPerformed(evt);
            }
        });
        panelBotones.add(btnTipoHabitaciones);

        btnReservas.setBackground(new java.awt.Color(204, 204, 204));
        btnReservas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(51, 51, 51));
        btnReservas.setText("Reservas");
        btnReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservasMouseClicked(evt);
            }
        });
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });
        panelBotones.add(btnReservas);

        btnClientes.setBackground(new java.awt.Color(204, 204, 204));
        btnClientes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelBotones.add(btnClientes);

        btnConfiguracion.setBackground(new java.awt.Color(204, 204, 204));
        btnConfiguracion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(51, 51, 51));
        btnConfiguracion.setText("Configuracion");
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseClicked(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        panelBotones.add(btnConfiguracion);

        panelMenu.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 427));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 190, -1));

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelMenu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 80, 25));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\PROYECTOS UNI\\Proyectos-Desktop\\SystemHotelReservas\\src\\main\\java\\Imagenes\\icons8-usuario-96.png")); // NOI18N
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 120));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 640));

        panelPaginas.setBackground(new java.awt.Color(153, 255, 51));
        panelPaginas.setAutoscrolls(true);
        panelPaginas.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1000, 640));

        jMenu2.setText("Themes");

        jMenuItem1.setText("White");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Black");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelInicio);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        interacionBontenes(btnInicio);
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        interacionBontenes(btnPerfil);
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void bntEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEmpleadoMouseClicked
        interacionBontenes(bntEmpleado);
    }//GEN-LAST:event_bntEmpleadoMouseClicked

    private void btnGestionHabiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionHabiMouseClicked
        interacionBontenes(btnGestionHabi);
    }//GEN-LAST:event_btnGestionHabiMouseClicked

    private void btnConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseClicked
        interacionBontenes(btnConfiguracion);
    }//GEN-LAST:event_btnConfiguracionMouseClicked

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed

// Asegúrate de usar GridLayout con una sola celda (1 fila, 1 columna)
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelPerfilAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();


    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnGestionHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionHabiActionPerformed

// Asegúrate de usar GridLayout con una sola celda (1 fila, 1 columna)
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelHabitacionesAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnGestionHabiActionPerformed

    private void bntEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEmpleadoActionPerformed

// Asegúrate de usar GridLayout con una sola celda (1 fila, 1 columna)
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelEmpleadoAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();

    }//GEN-LAST:event_bntEmpleadoActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        PanelConfiguracionAdm configuracionAdm = new PanelConfiguracionAdm();

        this.panelPaginas.removeAll();
        this.panelPaginas.add(configuracionAdm);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnTipoHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoHabitacionesActionPerformed

        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelTipoHabitacionesAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnTipoHabitacionesActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelRecervasAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnReservasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       // System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioKeyPressed

    }//GEN-LAST:event_btnInicioKeyPressed

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered

    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited

    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioKeyReleased

    }//GEN-LAST:event_btnInicioKeyReleased

    private void btnTipoHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoHabitacionesMouseClicked
        interacionBontenes(btnTipoHabitaciones);
    }//GEN-LAST:event_btnTipoHabitacionesMouseClicked

    private void btnReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseClicked
        interacionBontenes(btnReservas);
    }//GEN-LAST:event_btnReservasMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        interacionBontenes(btnClientes);
        this.panelPaginas.removeAll();
        this.panelPaginas.add(panelClientesAdm);
        this.panelPaginas.revalidate();
        this.panelPaginas.repaint();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmAdministradorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            FlatLightLaf.setup();
            //FlatDarkLaf.setup();
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("Button.arc", 20);
            UIManager.put("Componente.focusWidth", 0);
        } catch (Exception ex) {
            System.err.println("No se pudo inicializar el Look and Feel de FlatLaf.");
        }

        // Crear y mostrar la GUI de tu aplicación
        java.awt.EventQueue.invokeLater(() -> {
            // Inicializa y muestra tu ventana principal
            new JfrmAdministradorPrueba().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntEmpleado;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnGestionHabi;
    private javax.swing.JButton btnInicio;
    public javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReservas;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnTipoHabitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPaginas;
    // End of variables declaration//GEN-END:variables

    public void interacionBontenes(javax.swing.JButton button) {
        btnConfiguracion.setBackground(Color.WHITE);
        btnConfiguracion.setForeground(Color.BLACK);

        btnGestionHabi.setBackground(Color.WHITE);
        btnGestionHabi.setForeground(Color.BLACK);

        btnInicio.setBackground(Color.WHITE);
        btnInicio.setForeground(Color.BLACK);

        btnTipoHabitaciones.setBackground(Color.WHITE);
        btnTipoHabitaciones.setForeground(Color.BLACK);

        btnReservas.setBackground(Color.WHITE);
        btnReservas.setForeground(Color.BLACK);

        btnClientes.setBackground(Color.WHITE);
        btnClientes.setForeground(Color.BLACK);

        bntEmpleado.setBackground(Color.WHITE);
        bntEmpleado.setForeground(Color.BLACK);

        btnPerfil.setBackground(Color.WHITE);
        btnPerfil.setForeground(Color.BLACK);

        button.setBackground(Color.RED);
        button.setForeground(Color.WHITE);
    }
}
