/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Administrador.paneles;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.border.AbstractBorder;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import modelo.entity.Empleado;
import modelo.entity.Habitacion;
import modelo.entity.Roles;
import modelo.entity.TipoHabitacion;

/**
 * @author FranDev
 */
public class PanelHabitacionesAdm extends javax.swing.JPanel {

    public DefaultTableModel modTablaHabitaciones = new DefaultTableModel();

    /**
     * Creates new form PanelHabitacionesAdm
     */
    public PanelHabitacionesAdm() {
        initComponents();
        String cabeTableProduc[] = {"ID", "Número de Habitación", "Tipo de Habitación	", "Características", "Precio", "Estado"};
        darBordes(jpanelContenidoHabi);
        modTablaHabitaciones.setColumnIdentifiers(cabeTableProduc);
        busquedaDinamica();
        tablaHabitaciones.setModel(modTablaHabitaciones);

        tablaHabitaciones.setBackground(Color.BLACK);
        tablaHabitaciones.setForeground(Color.WHITE);

        Panel_RegistroHabitaciones.setVisible(false);
        Panel_EditHabitaciones.setVisible(false);
        Panel_Cancelar.setVisible(false);
        background.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Panel_Cancelar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        Panel_EditHabitaciones = new javax.swing.JPanel();
        btnAceptarEditHabitacion = new javax.swing.JButton();
        btnCancelarEditHabitacion = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtIdEditHabi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumeroHabitacionEdit = new javax.swing.JTextField();
        cboxEstadoEditHabi = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboxTipoHabitacionEditHabi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Panel_RegistroHabitaciones = new javax.swing.JPanel();
        btnAceptarGuardarHabitacion = new javax.swing.JButton();
        btnCancelarHabitacion = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtPrecioHabi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroHabitacionHi = new javax.swing.JTextField();
        cboxEstadoHabi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboxTipoHabitacionHabi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarHabi = new javax.swing.JButton();
        jpanelContenidoHabi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHabitaciones = new javax.swing.JTable();
        btnEliminarHabi = new javax.swing.JButton();
        txtBuscarHabitaciones = new javax.swing.JTextField();
        btnBuscarHabitacion = new javax.swing.JButton();
        btnEditarHabi = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(0, 0, 0, 150));
        background.setForeground(new java.awt.Color(153, 153, 153));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Panel_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Cancelar.setEnabled(false);
        Panel_Cancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("Confirmar Eliminación");
        Panel_Cancelar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("¿Esta usted seguro que desea eliminar esta reserva?");
        Panel_Cancelar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Esta acción no se puede deshacer");
        Panel_Cancelar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setActionCommand("CANCELAR");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        Panel_Cancelar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 30));

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.setActionCommand("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        Panel_Cancelar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 120, 30));

        background.add(Panel_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 420, 210));

        Panel_EditHabitaciones.setBackground(new java.awt.Color(255, 255, 255));
        Panel_EditHabitaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Panel_EditHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        Panel_EditHabitaciones.setEnabled(false);
        Panel_EditHabitaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarEditHabitacion.setBackground(new java.awt.Color(0, 255, 0));
        btnAceptarEditHabitacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAceptarEditHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarEditHabitacion.setText("ACEPTAR");
        btnAceptarEditHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptarEditHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditHabitacionActionPerformed(evt);
            }
        });
        Panel_EditHabitaciones.add(btnAceptarEditHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, 30));

        btnCancelarEditHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarEditHabitacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelarEditHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarEditHabitacion.setText("CANCELAR");
        btnCancelarEditHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditHabitacionActionPerformed(evt);
            }
        });
        Panel_EditHabitaciones.add(btnCancelarEditHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 150, 30));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ID Habitación");
        Panel_EditHabitaciones.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 20));

        txtIdEditHabi.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEditHabi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdEditHabi.setForeground(new java.awt.Color(0, 0, 0));
        txtIdEditHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEditHabiActionPerformed(evt);
            }
        });
        txtIdEditHabi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEditHabiKeyTyped(evt);
            }
        });
        Panel_EditHabitaciones.add(txtIdEditHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 150, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("N° Habitación");
        Panel_EditHabitaciones.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 20));

        txtNumeroHabitacionEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroHabitacionEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumeroHabitacionEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroHabitacionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroHabitacionEditActionPerformed(evt);
            }
        });
        txtNumeroHabitacionEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroHabitacionEditKeyTyped(evt);
            }
        });
        Panel_EditHabitaciones.add(txtNumeroHabitacionEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 160, -1));

        cboxEstadoEditHabi.setBackground(new java.awt.Color(255, 255, 255));
        cboxEstadoEditHabi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxEstadoEditHabi.setForeground(new java.awt.Color(0, 0, 0));
        cboxEstadoEditHabi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "DISPONIBLE", "OCUPADA", "RESERVADA", "OCUPADA", "MANTENIMIENTO" }));
        cboxEstadoEditHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEstadoEditHabiActionPerformed(evt);
            }
        });
        Panel_EditHabitaciones.add(cboxEstadoEditHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Estado");
        Panel_EditHabitaciones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, 20));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Tipo Habitación");
        Panel_EditHabitaciones.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 140, 20));

        cboxTipoHabitacionEditHabi.setBackground(new java.awt.Color(255, 255, 255));
        cboxTipoHabitacionEditHabi.setForeground(new java.awt.Color(0, 0, 0));
        cboxTipoHabitacionEditHabi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ACTIVO", "INACTIVO" }));
        cboxTipoHabitacionEditHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoHabitacionEditHabiActionPerformed(evt);
            }
        });
        Panel_EditHabitaciones.add(cboxTipoHabitacionEditHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 160, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Editar Habitación");
        Panel_EditHabitaciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        background.add(Panel_EditHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 470, 370));

        Panel_RegistroHabitaciones.setBackground(new java.awt.Color(255, 255, 255));
        Panel_RegistroHabitaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Panel_RegistroHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        Panel_RegistroHabitaciones.setEnabled(false);
        Panel_RegistroHabitaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarGuardarHabitacion.setBackground(new java.awt.Color(0, 255, 0));
        btnAceptarGuardarHabitacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAceptarGuardarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarGuardarHabitacion.setText("ACEPTAR");
        btnAceptarGuardarHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptarGuardarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarGuardarHabitacionActionPerformed(evt);
            }
        });
        Panel_RegistroHabitaciones.add(btnAceptarGuardarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, 30));

        btnCancelarHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarHabitacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarHabitacion.setText("CANCELAR");
        btnCancelarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarHabitacionActionPerformed(evt);
            }
        });
        Panel_RegistroHabitaciones.add(btnCancelarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 130, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Precio");
        Panel_RegistroHabitaciones.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, 20));

        txtPrecioHabi.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioHabi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioHabi.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioHabiActionPerformed(evt);
            }
        });
        txtPrecioHabi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioHabiKeyTyped(evt);
            }
        });
        Panel_RegistroHabitaciones.add(txtPrecioHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 150, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("N° Habitación");
        Panel_RegistroHabitaciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, 20));

        txtNumeroHabitacionHi.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroHabitacionHi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumeroHabitacionHi.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroHabitacionHi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroHabitacionHiActionPerformed(evt);
            }
        });
        txtNumeroHabitacionHi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroHabitacionHiKeyTyped(evt);
            }
        });
        Panel_RegistroHabitaciones.add(txtNumeroHabitacionHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, -1));

        cboxEstadoHabi.setBackground(new java.awt.Color(255, 255, 255));
        cboxEstadoHabi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxEstadoHabi.setForeground(new java.awt.Color(0, 0, 0));
        cboxEstadoHabi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "DISPONIBLE", "OCUPADA", "RESERVADA", "OCUPADA", "MANTENIMIENTO" }));
        cboxEstadoHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEstadoHabiActionPerformed(evt);
            }
        });
        Panel_RegistroHabitaciones.add(cboxEstadoHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 160, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Estado");
        Panel_RegistroHabitaciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tipo Habitación");
        Panel_RegistroHabitaciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 140, 20));

        cboxTipoHabitacionHabi.setBackground(new java.awt.Color(255, 255, 255));
        cboxTipoHabitacionHabi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxTipoHabitacionHabi.setForeground(new java.awt.Color(0, 0, 0));
        cboxTipoHabitacionHabi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cboxTipoHabitacionHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoHabitacionHabiActionPerformed(evt);
            }
        });
        Panel_RegistroHabitaciones.add(cboxTipoHabitacionHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Crear Nueva Habitación");
        Panel_RegistroHabitaciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        background.add(Panel_RegistroHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 470, 370));

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1000, 650));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de Habitaciones");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, 571, -1));

        btnAgregarHabi.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarHabi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregarHabi.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarHabi.setText("+ Añadir Habitacion");
        btnAgregarHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHabiActionPerformed(evt);
            }
        });
        add(btnAgregarHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 170, 48));

        jpanelContenidoHabi.setBackground(new java.awt.Color(255, 255, 255));
        jpanelContenidoHabi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpanelContenidoHabi.setForeground(new java.awt.Color(0, 0, 0));
        jpanelContenidoHabi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lista de Habitaciones");
        jpanelContenidoHabi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, 48));

        tablaHabitaciones.setBackground(new java.awt.Color(180, 180, 180));
        tablaHabitaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tablaHabitaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        tablaHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaHabitaciones.setGridColor(new java.awt.Color(180, 180, 180));
        jScrollPane1.setViewportView(tablaHabitaciones);

        jpanelContenidoHabi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 860, 190));

        btnEliminarHabi.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarHabi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminarHabi.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarHabi.setText("Eliminar");
        btnEliminarHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabiActionPerformed(evt);
            }
        });
        jpanelContenidoHabi.add(btnEliminarHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 120, 90, 35));

        txtBuscarHabitaciones.setBackground(new java.awt.Color(180, 180, 180));
        txtBuscarHabitaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarHabitaciones.setText("Buscar Habitacion");
        txtBuscarHabitaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarHabitacionesFocusLost(evt);
            }
        });
        txtBuscarHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarHabitacionesMouseClicked(evt);
            }
        });
        txtBuscarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarHabitacionesActionPerformed(evt);
            }
        });
        jpanelContenidoHabi.add(txtBuscarHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 276, 32));

        btnBuscarHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarHabitacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarHabitacion.setText("Buscar");
        btnBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabitacionActionPerformed(evt);
            }
        });
        jpanelContenidoHabi.add(btnBuscarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 86, 35));

        btnEditarHabi.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarHabi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarHabi.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarHabi.setText("Editar");
        btnEditarHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHabiActionPerformed(evt);
            }
        });
        jpanelContenidoHabi.add(btnEditarHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 86, 35));

        add(jpanelContenidoHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 950, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabiActionPerformed
        int fila = tablaHabitaciones.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showConfirmDialog(null, "SELECCIONA UN HABITACION   ", "", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);

        } else {
            bloquear(jpanelContenidoHabi);
            bloquearImputs();
            llenarFormEditar();
            background.setVisible(true);
            Panel_Cancelar.setVisible(true);
        }


    }//GEN-LAST:event_btnEliminarHabiActionPerformed

    private void btnBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarHabitacionActionPerformed

    private void btnAceptarGuardarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarGuardarHabitacionActionPerformed
        desbloquear(jpanelContenidoHabi);
        Panel_RegistroHabitaciones.setVisible(false);
        background.setVisible(false);

        //creamos una arreglo de tipos object
        //Object fila[] = new Object[7];
        // ArrayList<String> list = new ArrayList<>();
        //obtenemos los datos que agrega el usuario
        // String tDni = txtDni.getText();
        //String tNombre = txtNombre.getText();
        //String tApellido = txtApellido.getText();
        //  String puesto = (String) cboxPuesto.getSelectedItem();
        //  String tSalario = txtSalario.getText();
        //  String tTelefno = txtTelefono.getText();
        // list.add(tDni); //0
        // list.add(tNombre); //1
        // list.add(tApellido); //2
        //falta fecha de contratacion
        // list.add(puesto); //3
        //  list.add(tSalario);//4
        // list.add(tTelefno);//5
        //  administrador.registrarEmpleado(modTablaEmpleados, list);

        /*
        String tPuesto = String.valueOf(cboxPuesto.getSelectedItem());
        //
        Empleado empledo1 = new Mozo(tDni, tPuesto, 200, tNombre, tApellido, "", tTelefno, "");
        //        administrador.registrarEmpleado(empledo1);
        //"DNI","NOMBRE","APELLIDO","TELEFONO" ,"PUESTO","FECHA INGRESO","SALARIO"
        //agregamos cada ctenido al arreglo
        fila[0] = empledo1.getDni();
        fila[1] = empledo1.getNombre();
        fila[2] = empledo1.getApellido();
        fila[3] = empledo1.getCelular();
        fila[4] = empledo1.getPuesto();
        fila[5] = "200";
        fila[6] = empledo1.getSalario();
        //agregamos una fila  a la tabla con el contedio que tiene el arreglo
        modTablaEmpleados.addRow(fila);
         */
    }//GEN-LAST:event_btnAceptarGuardarHabitacionActionPerformed

    private void btnCancelarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarHabitacionActionPerformed
        desbloquear(jpanelContenidoHabi);
        Panel_RegistroHabitaciones.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnCancelarHabitacionActionPerformed

    private void btnAgregarHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHabiActionPerformed
        bloquear(jpanelContenidoHabi);
        background.setVisible(true);
        Panel_RegistroHabitaciones.setVisible(true);

    }//GEN-LAST:event_btnAgregarHabiActionPerformed

    private void txtPrecioHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioHabiActionPerformed

    private void txtPrecioHabiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioHabiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioHabiKeyTyped

    private void btnEditarHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHabiActionPerformed

        int fila = tablaHabitaciones.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showConfirmDialog(null, "SELECCIONA UN HABITACION   ", "", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);

        } else {
            bloquearImputs();
            bloquear(jpanelContenidoHabi);
            background.setVisible(true);
            Panel_EditHabitaciones.setVisible(true);
            llenarFormEditar();
        }
    }//GEN-LAST:event_btnEditarHabiActionPerformed

    private void txtNumeroHabitacionHiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionHiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHabitacionHiActionPerformed

    private void txtNumeroHabitacionHiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionHiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHabitacionHiKeyTyped

    private void cboxEstadoHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEstadoHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxEstadoHabiActionPerformed

    private void cboxTipoHabitacionHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoHabitacionHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoHabitacionHabiActionPerformed

    private void btnAceptarEditHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditHabitacionActionPerformed
        desbloquear(jpanelContenidoHabi);
        Panel_EditHabitaciones.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnAceptarEditHabitacionActionPerformed

    private void btnCancelarEditHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditHabitacionActionPerformed
        desbloquear(jpanelContenidoHabi);
        Panel_EditHabitaciones.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnCancelarEditHabitacionActionPerformed

    private void txtIdEditHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditHabiActionPerformed

    private void txtIdEditHabiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEditHabiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditHabiKeyTyped

    private void txtNumeroHabitacionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHabitacionEditActionPerformed

    private void txtNumeroHabitacionEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHabitacionEditKeyTyped

    private void cboxEstadoEditHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEstadoEditHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxEstadoEditHabiActionPerformed

    private void cboxTipoHabitacionEditHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoHabitacionEditHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoHabitacionEditHabiActionPerformed

    private void txtBuscarHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarHabitacionesMouseClicked
        if (txtBuscarHabitaciones.getText().equals("Buscar Habitacion")) {
            txtBuscarHabitaciones.setText("");
        }
        
        
        
    }//GEN-LAST:event_txtBuscarHabitacionesMouseClicked

    private void txtBuscarHabitacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarHabitacionesFocusLost
        if (txtBuscarHabitaciones.getText().isEmpty()) {
             txtBuscarHabitaciones.setText("Buscar Habitacion");
        }
    }//GEN-LAST:event_txtBuscarHabitacionesFocusLost

    private void txtBuscarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarHabitacionesActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // CANCELAR DE LA VENTANA CANCELAR
        
        Panel_Cancelar.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // SALIR DE LA VENTANA CANCELAR
        
        Panel_Cancelar.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_Cancelar;
    public javax.swing.JPanel Panel_EditHabitaciones;
    public javax.swing.JPanel Panel_RegistroHabitaciones;
    private javax.swing.JPanel background;
    public javax.swing.JButton btnAceptarEditHabitacion;
    public javax.swing.JButton btnAceptarGuardarHabitacion;
    public javax.swing.JButton btnAgregarHabi;
    public javax.swing.JButton btnBuscarHabitacion;
    public javax.swing.JButton btnCancelarEditHabitacion;
    public javax.swing.JButton btnCancelarHabitacion;
    public javax.swing.JButton btnEditarHabi;
    private javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminarHabi;
    private javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<String> cboxEstadoEditHabi;
    public javax.swing.JComboBox<String> cboxEstadoHabi;
    public javax.swing.JComboBox<String> cboxTipoHabitacionEditHabi;
    public javax.swing.JComboBox<String> cboxTipoHabitacionHabi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelContenidoHabi;
    public javax.swing.JTable tablaHabitaciones;
    private javax.swing.JTextField txtBuscarHabitaciones;
    public javax.swing.JTextField txtIdEditHabi;
    public javax.swing.JTextField txtNumeroHabitacionEdit;
    public javax.swing.JTextField txtNumeroHabitacionHi;
    public javax.swing.JTextField txtPrecioHabi;
    // End of variables declaration//GEN-END:variables
    public void bloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                bloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(false);

    }

    public void desbloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                desbloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(true);

    }

    public Empleado getDatosEmpleado() {
        Empleado emVista = new Empleado();

        List<Roles> assginedRoles = new ArrayList<>();
        Roles rol = new Roles();

        //  rol.setNombreRol((String) cboxTipoHabi.getSelectedItem());
        assginedRoles.add(rol);

        emVista.setRoles(assginedRoles);

        return emVista;
    }

    public boolean validarCampos() {
        /*
        if (txtApellidoEm.getText().trim().isEmpty()
                || txtCorreoEm.getText().trim().isEmpty()
                || txtCaracteristicasHabi.getText().trim().isEmpty()
                || txtDniEm.getText().trim().isEmpty()
                || txtNombreEm.getText().trim().isEmpty()
                || txtPasswordEm.getText().trim().isEmpty()
                || txtPrecioHabi.getText().trim().isEmpty()) {

            //javax.swing.JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Error de Validación", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
         */
        return true;
    }

    public void bloquearImputs() {

        txtIdEditHabi.setEnabled(false);

    }

    public void desbloquearImputs() {

        //  txtDniEm.setEnabled(true);
        // txtNombreEm.setEnabled(true);
        // txtApellidoEm.setEnabled(true);
        // txtCorreoEm.
        // txtDireccionEm.
        // txtDniEm.
        // txtNombreEm.
        // txtPasswordEm.
        // txtTelefonoEm.
    }

    public void llenarFormEditar() {

        /*


         */
        int fila = tablaHabitaciones.getSelectedRow();

        String idHabitacion = String.valueOf(tablaHabitaciones.getValueAt(fila, 0));
        String numeroHabitacion = String.valueOf(tablaHabitaciones.getValueAt(fila, 1));

        txtIdEditHabi.setText(idHabitacion);
        txtNumeroHabitacionEdit.setText(numeroHabitacion);

    }

    public Habitacion datosSaveHabitacion() {
        Habitacion dataHabitacion = new Habitacion();
        TipoHabitacion tipoHabitacion = new TipoHabitacion();

        dataHabitacion.setNumeroDeHabitacion(txtNumeroHabitacionHi.getText());
        dataHabitacion.setEstado(cboxEstadoHabi.getSelectedItem().toString());

        tipoHabitacion.setTipoHabitacion(cboxTipoHabitacionHabi.getSelectedItem().toString());

        dataHabitacion.setTipoHabitacion(tipoHabitacion);

        return dataHabitacion;
    }

    public Habitacion datosUpdateHabitacion() {
        Habitacion dataHabitacion = new Habitacion();
        TipoHabitacion tipoHabitacion = new TipoHabitacion();

        dataHabitacion.setIdHabitacion(Long.valueOf(txtIdEditHabi.getText()));
        dataHabitacion.setNumeroDeHabitacion(txtNumeroHabitacionEdit.getText());
        dataHabitacion.setEstado(cboxEstadoEditHabi.getSelectedItem().toString());
        tipoHabitacion.setTipoHabitacion(cboxTipoHabitacionEditHabi.getSelectedItem().toString());

        dataHabitacion.setTipoHabitacion(tipoHabitacion);

        return dataHabitacion;
    }

    public void darBordes(JPanel jPanel) {
        // Crear una clase interna para el borde redondeado
        class BordeRedondeado extends AbstractBorder {

            private int radio;
            private Color color;
            private int grosor;

            public BordeRedondeado(int radio, Color color, int grosor) {
                this.radio = radio;
                this.color = color;
                this.grosor = grosor;
            }

            @Override
            public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); // Suaviza bordes
                g2.setColor(color);
                g2.setStroke(new BasicStroke(grosor));
                g2.drawRoundRect(x + grosor / 2, y + grosor / 2, width - grosor, height - grosor, radio, radio); // Esquinas redondeadas
            }

            @Override
            public Insets getBorderInsets(Component c) {
                return new Insets(grosor, grosor, grosor, grosor); // Margen del borde
            }

            @Override
            public boolean isBorderOpaque() {
                return true;
            }
        }

        // Aplicar el borde redondeado al JPanel
        jPanel.setBorder(new BordeRedondeado(20, Color.BLACK, 2));
    }

    public void busquedaDinamica() {
        // Crear un TableRowSorter para el modelo de la tabla
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modTablaHabitaciones);
        tablaHabitaciones.setRowSorter(sorter);

        // Añadir un KeyListener al campo de búsqueda
        txtBuscarHabitaciones.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String textoBusqueda = txtBuscarHabitaciones.getText().trim();

                // Si el campo de búsqueda está vacío, mostrar todas las filas
                if (textoBusqueda.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    // Aplicar un filtro en la tabla según el texto ingresado
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
                }
            }
        });

    }
}
