/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Empleado.paneles;

import java.awt.GridLayout;

/**
 *
 * @author Lesli
 */
public class PanelEditar extends javax.swing.JPanel {

    /**
     * Creates new form PanelEditar
     */
    public PanelEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTxtCodigo2 = new javax.swing.JTextField();
        jBBuscar2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTxtNombre2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTxtDni2 = new javax.swing.JTextField();
        jTxtNroPersonas2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTxtTelefono4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTxtCorreo4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTxtTipoHbi4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTxtllegada2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTxtfin2 = new javax.swing.JTextField();
        jTxtPrecio2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jBCancelar2 = new javax.swing.JButton();
        jBActualizar2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(520, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel25.setText("Editar Reserva");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel32.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel32.setText("Código");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTxtCodigo2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtCodigo2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtCodigo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCodigo2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 102, 26));

        jBBuscar2.setBackground(new java.awt.Color(0, 0, 0));
        jBBuscar2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jBBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        jBBuscar2.setText("Buscar");
        jBBuscar2.setBorder(null);
        jBBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        add(jBBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 58, 22));

        jLabel33.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel33.setText("Nombre Completo");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jTxtNombre2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtNombre2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtNombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtNombre2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 315, 26));

        jLabel31.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel31.setText("DNI");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jTxtDni2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtDni2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtDni2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtDni2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 139, 26));

        jTxtNroPersonas2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtNroPersonas2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtNroPersonas2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtNroPersonas2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtNroPersonas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 83, 26));

        jLabel34.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel34.setText("N° de Personas");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel35.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel35.setText("Telefono");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTxtTelefono4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtTelefono4.setForeground(new java.awt.Color(51, 51, 51));
        jTxtTelefono4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtTelefono4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtTelefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 139, 26));

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel26.setText("Correo Electronico");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jTxtCorreo4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtCorreo4.setForeground(new java.awt.Color(51, 51, 51));
        jTxtCorreo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCorreo4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtCorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 210, 26));

        jLabel27.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Tipo de Habitación");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jTxtTipoHbi4.setBackground(new java.awt.Color(153, 153, 153));
        jTxtTipoHbi4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtTipoHbi4.setForeground(new java.awt.Color(51, 51, 51));
        jTxtTipoHbi4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtTipoHbi4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTxtTipoHbi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTipoHbi2ActionPerformed(evt);
            }
        });
        add(jTxtTipoHbi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 139, 26));

        jLabel28.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel28.setText("Fecha de llegada");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jTxtllegada2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtllegada2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtllegada2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtllegada2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtllegada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 139, 26));

        jLabel29.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel29.setText("Fecha de fin");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jTxtfin2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtfin2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtfin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtfin2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtfin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 139, 26));

        jTxtPrecio2.setBackground(new java.awt.Color(153, 153, 153));
        jTxtPrecio2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTxtPrecio2.setForeground(new java.awt.Color(51, 51, 51));
        jTxtPrecio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtPrecio2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTxtPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 139, 26));

        jLabel30.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("Precio");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jBCancelar2.setBackground(new java.awt.Color(51, 51, 51));
        jBCancelar2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jBCancelar2.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar2.setText("Cancelar");
        jBCancelar2.setBorder(null);
        jBCancelar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCancelar2.setPreferredSize(new java.awt.Dimension(49, 15));
        jBCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        add(jBCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 79, 30));

        jBActualizar2.setBackground(new java.awt.Color(0, 0, 0));
        jBActualizar2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jBActualizar2.setForeground(new java.awt.Color(255, 255, 255));
        jBActualizar2.setText("Actualizar");
        jBActualizar2.setBorder(null);
        jBActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        add(jBActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 31));
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
       PanelReservas panelReservas = new PanelReservas();

        this.setLayout(new GridLayout(1, 1));

        this.removeAll();
        this.add(panelReservas);
        this.revalidate();
        this.repaint();
        
        
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTxtTipoHbi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTipoHbi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTipoHbi2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel bg3;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBActualizar1;
    private javax.swing.JButton jBActualizar2;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscar1;
    private javax.swing.JButton jBBuscar2;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBCancelar1;
    private javax.swing.JButton jBCancelar2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtCodigo1;
    private javax.swing.JTextField jTxtCodigo2;
    private javax.swing.JTextField jTxtCorreo2;
    private javax.swing.JTextField jTxtCorreo3;
    private javax.swing.JTextField jTxtCorreo4;
    private javax.swing.JTextField jTxtDni;
    private javax.swing.JTextField jTxtDni1;
    private javax.swing.JTextField jTxtDni2;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtNombre1;
    private javax.swing.JTextField jTxtNombre2;
    private javax.swing.JTextField jTxtNroPersonas;
    private javax.swing.JTextField jTxtNroPersonas1;
    private javax.swing.JTextField jTxtNroPersonas2;
    private javax.swing.JTextField jTxtPrecio;
    private javax.swing.JTextField jTxtPrecio1;
    private javax.swing.JTextField jTxtPrecio2;
    private javax.swing.JTextField jTxtTelefono2;
    private javax.swing.JTextField jTxtTelefono3;
    private javax.swing.JTextField jTxtTelefono4;
    private javax.swing.JTextField jTxtTipoHbi2;
    private javax.swing.JTextField jTxtTipoHbi3;
    private javax.swing.JTextField jTxtTipoHbi4;
    private javax.swing.JTextField jTxtfin;
    private javax.swing.JTextField jTxtfin1;
    private javax.swing.JTextField jTxtfin2;
    private javax.swing.JTextField jTxtllegada;
    private javax.swing.JTextField jTxtllegada1;
    private javax.swing.JTextField jTxtllegada2;
    // End of variables declaration//GEN-END:variables
}
