/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Empleado.paneles;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.border.AbstractBorder;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import modelo.entity.Empleado;
import modelo.entity.Habitacion;
import modelo.entity.Roles;
import modelo.entity.TipoHabitacion;

/**
 * @author FranDev
 */
public class PanelClientesRecep extends javax.swing.JPanel {

    public DefaultTableModel modTablaClientes = new DefaultTableModel();

    /**
     * Creates new form PanelHabitacionesAdm
     */
    public PanelClientesRecep() {
        initComponents();
        String cabeTableProduc[] = {"ID", "Nombre", "Apellido", "Dni", "Correo Electronico", "Telefono"};
        darBordes(jpanelContenidoHabi);
        modTablaClientes.setColumnIdentifiers(cabeTableProduc);
        busquedaDinamica();
        tablaClientes.setModel(modTablaClientes);

        tablaClientes.setBackground(Color.BLACK);
        tablaClientes.setForeground(Color.WHITE);

        Panel_EditarCliente.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panel_EditarCliente = new javax.swing.JPanel();
        btnAceptarGuardarCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEditPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEditLastName = new javax.swing.JTextField();
        txtEditEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        txtEditDocument = new javax.swing.JTextField();
        jpanelContenidoHabi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        txtBuscarReservas = new javax.swing.JTextField();
        btnEditClient = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Clientes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, 571, -1));

        Panel_EditarCliente.setBackground(new java.awt.Color(255, 255, 255));
        Panel_EditarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Panel_EditarCliente.setForeground(new java.awt.Color(0, 0, 0));
        Panel_EditarCliente.setEnabled(false);
        Panel_EditarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarGuardarCliente.setBackground(new java.awt.Color(0, 255, 0));
        btnAceptarGuardarCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAceptarGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarGuardarCliente.setText("ACEPTAR");
        btnAceptarGuardarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptarGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarGuardarClienteActionPerformed(evt);
            }
        });
        Panel_EditarCliente.add(btnAceptarGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 140, 30));

        btnCancelarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCliente.setText("CANCELAR");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });
        Panel_EditarCliente.add(btnCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 140, 30));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Teléfono");
        Panel_EditarCliente.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 110, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre");
        Panel_EditarCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 20));

        txtEditPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtEditPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtEditPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditPhoneActionPerformed(evt);
            }
        });
        txtEditPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditPhoneKeyTyped(evt);
            }
        });
        Panel_EditarCliente.add(txtEditPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Dni");
        Panel_EditarCliente.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Editar Cliente");
        Panel_EditarCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 50));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Apellido");
        Panel_EditarCliente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 90, 20));

        txtEditLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtEditLastName.setForeground(new java.awt.Color(0, 0, 0));
        txtEditLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditLastNameActionPerformed(evt);
            }
        });
        txtEditLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditLastNameKeyTyped(evt);
            }
        });
        Panel_EditarCliente.add(txtEditLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, -1));

        txtEditEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEditEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditEmailActionPerformed(evt);
            }
        });
        txtEditEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditEmailKeyTyped(evt);
            }
        });
        Panel_EditarCliente.add(txtEditEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 380, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Correo Electrónico");
        Panel_EditarCliente.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 340, 20));

        txtEditName.setBackground(new java.awt.Color(255, 255, 255));
        txtEditName.setForeground(new java.awt.Color(0, 0, 0));
        txtEditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditNameActionPerformed(evt);
            }
        });
        txtEditName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditNameKeyTyped(evt);
            }
        });
        Panel_EditarCliente.add(txtEditName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 170, -1));

        txtEditDocument.setBackground(new java.awt.Color(255, 255, 255));
        txtEditDocument.setForeground(new java.awt.Color(0, 0, 0));
        txtEditDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditDocumentActionPerformed(evt);
            }
        });
        txtEditDocument.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditDocumentKeyTyped(evt);
            }
        });
        Panel_EditarCliente.add(txtEditDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, -1));

        add(Panel_EditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 470, 370));

        jpanelContenidoHabi.setBackground(new java.awt.Color(255, 255, 255));
        jpanelContenidoHabi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpanelContenidoHabi.setForeground(new java.awt.Color(0, 0, 0));
        jpanelContenidoHabi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lista de Clientes");
        jpanelContenidoHabi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, 48));
        jpanelContenidoHabi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 7, -1, -1));

        tablaClientes.setBackground(new java.awt.Color(180, 180, 180));
        tablaClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tablaClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaClientes.setGridColor(new java.awt.Color(180, 180, 180));
        jScrollPane1.setViewportView(tablaClientes);

        jpanelContenidoHabi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 750, 200));

        txtBuscarReservas.setBackground(new java.awt.Color(180, 180, 180));
        txtBuscarReservas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarReservas.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarReservas.setText("Buscar cliente");
        txtBuscarReservas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarReservasFocusLost(evt);
            }
        });
        txtBuscarReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarReservasMouseClicked(evt);
            }
        });
        txtBuscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarReservasActionPerformed(evt);
            }
        });
        jpanelContenidoHabi.add(txtBuscarReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 74, 276, 32));

        btnEditClient.setBackground(new java.awt.Color(0, 0, 0));
        btnEditClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditClient.setForeground(new java.awt.Color(255, 255, 255));
        btnEditClient.setText("Editar");
        btnEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientActionPerformed(evt);
            }
        });
        jpanelContenidoHabi.add(btnEditClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 86, 35));

        add(jpanelContenidoHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 800, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientActionPerformed
        bloquearImputs();

        int fila = tablaClientes.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showConfirmDialog(null, "SELECCIONA UNA FILA PARA CONTINUAR", "", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);

        } else {
            bloquear(jpanelContenidoHabi);
            bloquearImputs();
            llenarFormEditar();
            bloquearTablaEmpleados();
            Panel_EditarCliente.setVisible(true);
        }
    }//GEN-LAST:event_btnEditClientActionPerformed

    private void btnAceptarGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarGuardarClienteActionPerformed
        desbloquear(jpanelContenidoHabi);
        Panel_EditarCliente.setVisible(false);

        //creamos una arreglo de tipos object
        //Object fila[] = new Object[7];
        // ArrayList<String> list = new ArrayList<>();
        //obtenemos los datos que agrega el usuario
        // String tDni = txtDni.getText();
        //String tNombre = txtNombre.getText();
        //String tApellido = txtApellido.getText();
        //  String puesto = (String) cboxPuesto.getSelectedItem();
        //  String tSalario = txtSalario.getText();
        //  String tTelefno = txtTelefono.getText();
        // list.add(tDni); //0
        // list.add(tNombre); //1
        // list.add(tApellido); //2
        //falta fecha de contratacion
        // list.add(puesto); //3
        //  list.add(tSalario);//4
        // list.add(tTelefno);//5
        //  administrador.registrarEmpleado(modTablaEmpleados, list);

        /*
        String tPuesto = String.valueOf(cboxPuesto.getSelectedItem());
        //
        Empleado empledo1 = new Mozo(tDni, tPuesto, 200, tNombre, tApellido, "", tTelefno, "");
        //        administrador.registrarEmpleado(empledo1);
        //"DNI","NOMBRE","APELLIDO","TELEFONO" ,"PUESTO","FECHA INGRESO","SALARIO"
        //agregamos cada ctenido al arreglo
        fila[0] = empledo1.getDni();
        fila[1] = empledo1.getNombre();
        fila[2] = empledo1.getApellido();
        fila[3] = empledo1.getCelular();
        fila[4] = empledo1.getPuesto();
        fila[5] = "200";
        fila[6] = empledo1.getSalario();
        //agregamos una fila  a la tabla con el contedio que tiene el arreglo
        modTablaEmpleados.addRow(fila);
         */
    }//GEN-LAST:event_btnAceptarGuardarClienteActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        desbloquear(jpanelContenidoHabi);
        desbloquearTablaEmpleados();
        Panel_EditarCliente.setVisible(false);
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void txtEditPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditPhoneActionPerformed

    private void txtEditPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditPhoneKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditPhoneKeyTyped

    private void txtBuscarReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarReservasMouseClicked
        if (txtBuscarReservas.getText().equals("Buscar Reserva")) {
            txtBuscarReservas.setText("");
        }
    }//GEN-LAST:event_txtBuscarReservasMouseClicked

    private void txtBuscarReservasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarReservasFocusLost
        if (txtBuscarReservas.getText().isEmpty()) {
             txtBuscarReservas.setText("Buscar Reserva");
        }
    }//GEN-LAST:event_txtBuscarReservasFocusLost

    private void txtBuscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarReservasActionPerformed

    private void txtEditLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditLastNameActionPerformed

    private void txtEditLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditLastNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditLastNameKeyTyped

    private void txtEditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditEmailActionPerformed

    private void txtEditEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditEmailKeyTyped

    private void txtEditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditNameActionPerformed

    private void txtEditNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditNameKeyTyped

    private void txtEditDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditDocumentActionPerformed

    private void txtEditDocumentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditDocumentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditDocumentKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_EditarCliente;
    public javax.swing.JButton btnAceptarGuardarCliente;
    public javax.swing.JButton btnCancelarCliente;
    public javax.swing.JButton btnEditClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelContenidoHabi;
    public javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtBuscarReservas;
    public javax.swing.JTextField txtEditDocument;
    public javax.swing.JTextField txtEditEmail;
    public javax.swing.JTextField txtEditLastName;
    public javax.swing.JTextField txtEditName;
    public javax.swing.JTextField txtEditPhone;
    // End of variables declaration//GEN-END:variables
    public void bloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                bloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(false);

    }

    public void desbloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                desbloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(true);

    }

    public Empleado getDatosEmpleado() {
        Empleado emVista = new Empleado();

        List<Roles> assginedRoles = new ArrayList<>();
        Roles rol = new Roles();

        //  rol.setNombreRol((String) cboxTipoHabi.getSelectedItem());
        assginedRoles.add(rol);

        emVista.setRoles(assginedRoles);

        return emVista;
    }

    public boolean validarCampos() {
        /*
        if (txtApellidoEm.getText().trim().isEmpty()
                || txtCorreoEm.getText().trim().isEmpty()
                || txtCaracteristicasHabi.getText().trim().isEmpty()
                || txtDniEm.getText().trim().isEmpty()
                || txtNombreEm.getText().trim().isEmpty()
                || txtPasswordEm.getText().trim().isEmpty()
                || txtPrecioHabi.getText().trim().isEmpty()) {

            //javax.swing.JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Error de Validación", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
         */
        return true;
    }

    public void bloquearImputs() {
        txtEditDocument.setEnabled(false);
    }

    public void desbloquearImputs() {

        //  txtDniEm.setEnabled(true);
        // txtNombreEm.setEnabled(true);
        // txtApellidoEm.setEnabled(true);
        // txtCorreoEm.
        // txtDireccionEm.
        // txtDniEm.
        // txtNombreEm.
        // txtPasswordEm.
        // txtTelefonoEm.
    }

    public void llenarFormEditar() {
        int fila = tablaClientes.getSelectedRow();

        String clientName = String.valueOf(tablaClientes.getValueAt(fila, 1));
        String clientLastName = String.valueOf(tablaClientes.getValueAt(fila, 2));
        String clientDocument = String.valueOf(tablaClientes.getValueAt(fila, 3));
        String clientPhone = String.valueOf(tablaClientes.getValueAt(fila, 4));
        String clientEmail = String.valueOf(tablaClientes.getValueAt(fila, 5));
        
        txtEditName.setText(clientName);
        txtEditLastName.setText(clientLastName);
        txtEditDocument.setText(clientDocument);
        txtEditPhone.setText(clientPhone);
        txtEditEmail.setText(clientEmail);
    }

    public Habitacion datosSaveHabitacion() {
        Habitacion dataHabitacion = new Habitacion();
        TipoHabitacion tipoHabitacion = new TipoHabitacion();

        dataHabitacion.setNumeroDeHabitacion(txtEditPhone.getText());

        dataHabitacion.setTipoHabitacion(tipoHabitacion);

        return dataHabitacion;
    }

    public Habitacion datosUpdateHabitacion() {
        Habitacion dataHabitacion = new Habitacion();

        return dataHabitacion;
    }

    public void darBordes(JPanel jPanel) {
        // Crear una clase interna para el borde redondeado
        class BordeRedondeado extends AbstractBorder {

            private int radio;
            private Color color;
            private int grosor;

            public BordeRedondeado(int radio, Color color, int grosor) {
                this.radio = radio;
                this.color = color;
                this.grosor = grosor;
            }

            @Override
            public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); // Suaviza bordes
                g2.setColor(color);
                g2.setStroke(new BasicStroke(grosor));
                g2.drawRoundRect(x + grosor / 2, y + grosor / 2, width - grosor, height - grosor, radio, radio); // Esquinas redondeadas
            }

            @Override
            public Insets getBorderInsets(Component c) {
                return new Insets(grosor, grosor, grosor, grosor); // Margen del borde
            }

            @Override
            public boolean isBorderOpaque() {
                return true;
            }
        }

        // Aplicar el borde redondeado al JPanel
        jPanel.setBorder(new BordeRedondeado(20, Color.BLACK, 2));
    }
    
    
    public void busquedaDinamica() {
        // Crear un TableRowSorter para el modelo de la tabla
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modTablaClientes);
        tablaClientes.setRowSorter(sorter);

        // Añadir un KeyListener al campo de búsqueda
        txtBuscarReservas.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String textoBusqueda = txtBuscarReservas.getText().trim();

                // Si el campo de búsqueda está vacío, mostrar todas las filas
                if (textoBusqueda.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    // Aplicar un filtro en la tabla según el texto ingresado
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
                }
            }
        });
    }
    
    public void bloquearTablaEmpleados() {
        // Obtener el JScrollPane que contiene la tabla
        JScrollPane scrollPane = (JScrollPane) tablaClientes.getParent().getParent();

        // Deshabilitar el desplazamiento
        scrollPane.setWheelScrollingEnabled(false); // Deshabilita el scroll con el ratón
        scrollPane.getVerticalScrollBar().setEnabled(false); // Deshabilita la barra de desplazamiento vertical
        scrollPane.getHorizontalScrollBar().setEnabled(false); // Deshabilita la barra de desplazamiento horizontal

        // También, puedes deshabilitar la tabla completamente, para evitar que interactúen con la misma
        tablaClientes.setEnabled(false); // Deshabilita la interacción con la tabla
    }
    
    public void desbloquearTablaEmpleados() {
        // Obtener el JScrollPane que contiene la tabla
        JScrollPane scrollPane = (JScrollPane) tablaClientes.getParent().getParent();

        // Deshabilitar el desplazamiento
        scrollPane.setWheelScrollingEnabled(true); // Deshabilita el scroll con el ratón
        scrollPane.getVerticalScrollBar().setEnabled(true); // Deshabilita la barra de desplazamiento vertical
        scrollPane.getHorizontalScrollBar().setEnabled(true); // Deshabilita la barra de desplazamiento horizontal

        // También, puedes deshabilitar la tabla completamente, para evitar que interactúen con la misma
        tablaClientes.setEnabled(true); // Deshabilita la interacción con la tabla

    }
        
}
