/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Empleado.paneles;

import java.awt.Component;
import java.awt.Container;


/**
 *
 * @author FranDev
 */
public class PanelReservas extends javax.swing.JPanel {

    /**
     * Creates new form PanelReservas
     */
    public PanelReservas() {
        initComponents();
        Panel_Cancelar.setVisible(false);
        Panel_Editar.setVisible(false);
        background.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        PanelBotones = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        Panel_Cancelar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        btnCancelar_PanelCancelar = new javax.swing.JButton();
        btnSalir_PanelCancelar = new javax.swing.JButton();
        Panel_Editar = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btnCancelar_PanelEditar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        btnEditar_PanelEditar1 = new javax.swing.JButton();
        btnActualizar_PanelEditar1 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cboxRoles = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setPreferredSize(new java.awt.Dimension(700, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBotones.setBackground(new java.awt.Color(235, 235, 235));
        PanelBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelBotones.setForeground(new java.awt.Color(0, 0, 0));
        PanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204, 150));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setToolTipText("Buscar");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setName(""); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelBotones.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 189, 31));
        jTextField1.getAccessibleContext().setAccessibleName("Buscar");

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        PanelBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        jTable1.setBackground(new java.awt.Color(180, 180, 180));
        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Cliente", "Fecha de Registro", "Fecha de Llegada", "Fecha de Finalizacion", "Codigo", "Persona", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(180, 180, 180));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(1).setMinWidth(120);
            jTable1.getColumnModel().getColumn(2).setMinWidth(105);
            jTable1.getColumnModel().getColumn(3).setMinWidth(110);
            jTable1.getColumnModel().getColumn(4).setMinWidth(120);
        }

        PanelBotones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 652, 243));

        btnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        PanelBotones.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnEditar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        PanelBotones.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 80, -1));

        add(PanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 790, 350));

        background.setBackground(new java.awt.Color(0, 0, 0, 150));
        background.setForeground(new java.awt.Color(153, 153, 153));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Panel_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Cancelar.setEnabled(false);
        Panel_Cancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Confirmar Cancelación");
        Panel_Cancelar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("¿Esta usted seguro que desea eliminar esta reserva?");
        Panel_Cancelar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Esta acción no se puede deshacer");
        Panel_Cancelar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        Panel_Cancelar.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DNI");
        Panel_Cancelar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cliente");
        Panel_Cancelar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jTextField12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(102, 102, 102));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField12.setAutoscrolls(false);
        jTextField12.setEnabled(false);
        jTextField12.setFocusable(false);
        jTextField12.setRequestFocusEnabled(false);
        Panel_Cancelar.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, -1));

        btnCancelar_PanelCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar_PanelCancelar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnCancelar_PanelCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar_PanelCancelar.setText("Cancelar");
        btnCancelar_PanelCancelar.setActionCommand("CANCELAR");
        btnCancelar_PanelCancelar.setBorder(null);
        btnCancelar_PanelCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_PanelCancelarActionPerformed(evt);
            }
        });
        Panel_Cancelar.add(btnCancelar_PanelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 30));

        btnSalir_PanelCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir_PanelCancelar.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnSalir_PanelCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir_PanelCancelar.setText("Salir");
        btnSalir_PanelCancelar.setActionCommand("SALIR");
        btnSalir_PanelCancelar.setBorder(null);
        btnSalir_PanelCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir_PanelCancelarActionPerformed(evt);
            }
        });
        Panel_Cancelar.add(btnSalir_PanelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 120, 30));
        btnSalir_PanelCancelar.getAccessibleContext().setAccessibleName("SALIR");

        background.add(Panel_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 420, 210));

        Panel_Editar.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Editar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Panel_Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Editar.setEnabled(false);
        Panel_Editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Editar Reserva");
        Panel_Editar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Apellido");
        Panel_Editar.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Telefono");
        Panel_Editar.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Correo Electronico");
        Panel_Editar.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Tipo de Habitación");
        Panel_Editar.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Fecha de llegada");
        Panel_Editar.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Fecha de fin");
        Panel_Editar.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Precio");
        Panel_Editar.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("DNI");
        Panel_Editar.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btnCancelar_PanelEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar_PanelEditar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelar_PanelEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar_PanelEditar.setText("Cancelar");
        btnCancelar_PanelEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_PanelEditarActionPerformed(evt);
            }
        });
        Panel_Editar.add(btnCancelar_PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 120, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, 30));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, 30));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, 30));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        Panel_Editar.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 180, 30));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, 30));

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 140, 30));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 0, 0));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 140, 30));

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 130, 30));

        btnEditar_PanelEditar1.setBackground(new java.awt.Color(51, 51, 51));
        btnEditar_PanelEditar1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEditar_PanelEditar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar_PanelEditar1.setText("Buscar");
        btnEditar_PanelEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar_PanelEditar1ActionPerformed(evt);
            }
        });
        Panel_Editar.add(btnEditar_PanelEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        btnActualizar_PanelEditar1.setBackground(new java.awt.Color(51, 51, 51));
        btnActualizar_PanelEditar1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnActualizar_PanelEditar1.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar_PanelEditar1.setText("Actualizar");
        btnActualizar_PanelEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_PanelEditar1ActionPerformed(evt);
            }
        });
        Panel_Editar.add(btnActualizar_PanelEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 120, 30));

        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Panel_Editar.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 30));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Nombre ");
        Panel_Editar.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        cboxRoles.setBackground(new java.awt.Color(255, 255, 255));
        cboxRoles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxRoles.setForeground(new java.awt.Color(0, 0, 0));
        cboxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cboxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRolesActionPerformed(evt);
            }
        });
        Panel_Editar.add(cboxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 160, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Habitacion");
        Panel_Editar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 80, 20));

        background.add(Panel_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 550, 450));

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1070, 690));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Reservas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bloquear(PanelBotones);
        background.setVisible(true);
        Panel_Cancelar.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        bloquear(PanelBotones);
        background.setVisible(true);
        Panel_Editar.setVisible(true);

        //creamos una arreglo de tipos object
        //Object fila[] = new Object[7];
        // ArrayList<String> list = new ArrayList<>();
        //obtenemos los datos que agrega el usuario
        // String tDni = txtDni.getText();
        //String tNombre = txtNombre.getText();
        //String tApellido = txtApellido.getText();
        //  String puesto = (String) cboxPuesto.getSelectedItem();
        //  String tSalario = txtSalario.getText();
        //  String tTelefno = txtTelefono.getText();
        // list.add(tDni); //0
        // list.add(tNombre); //1
        // list.add(tApellido); //2
        //falta fecha de contratacion
        // list.add(puesto); //3
        //  list.add(tSalario);//4
        // list.add(tTelefno);//5
        //  administrador.registrarEmpleado(modTablaEmpleados, list);

        /*
        String tPuesto = String.valueOf(cboxPuesto.getSelectedItem());
        //
        Empleado empledo1 = new Mozo(tDni, tPuesto, 200, tNombre, tApellido, "", tTelefno, "");
        //        administrador.registrarEmpleado(empledo1);
        //"DNI","NOMBRE","APELLIDO","TELEFONO" ,"PUESTO","FECHA INGRESO","SALARIO"
        //agregamos cada ctenido al arreglo
        fila[0] = empledo1.getDni();
        fila[1] = empledo1.getNombre();
        fila[2] = empledo1.getApellido();
        fila[3] = empledo1.getCelular();
        fila[4] = empledo1.getPuesto();
        fila[5] = "200";
        fila[6] = empledo1.getSalario();
        //agregamos una fila  a la tabla con el contedio que tiene el arreglo
        modTablaEmpleados.addRow(fila);
        */
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
  
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    
    // PANEL EDITAR RESERVA !!!
    private void btnCancelar_PanelEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_PanelEditarActionPerformed
        desbloquear(PanelBotones);
        Panel_Editar.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnCancelar_PanelEditarActionPerformed

    private void btnEditar_PanelEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar_PanelEditar1ActionPerformed
        // BUSCAR POR DNI DE LA VENTANA EDITAR
    }//GEN-LAST:event_btnEditar_PanelEditar1ActionPerformed

    private void btnActualizar_PanelEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_PanelEditar1ActionPerformed
        // ACTUALIZAR DE LA VENTANA EDITAR
        desbloquear(PanelBotones);
        Panel_Editar.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnActualizar_PanelEditar1ActionPerformed
    
    // PANEL CONFIRMAR CANCELACIÓN !!!!
    private void btnCancelar_PanelCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_PanelCancelarActionPerformed
        // CANCELAR DE LA VENTANA CANCELAR
        desbloquear(PanelBotones);
        Panel_Cancelar.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnCancelar_PanelCancelarActionPerformed

    private void btnSalir_PanelCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir_PanelCancelarActionPerformed
        // SALIR DE LA VENTANA CANCELAR
        desbloquear(PanelBotones);
        Panel_Cancelar.setVisible(false);
        background.setVisible(false);
    }//GEN-LAST:event_btnSalir_PanelCancelarActionPerformed

    private void cboxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRolesActionPerformed
        cboxRoles.getSelectedItem();
        if (cboxRoles.getSelectedIndex() == 1 || cboxRoles.getSelectedIndex() == 2 || cboxRoles.getSelectedIndex() == 3) {
            // txtSalario.setText("1200");

        } else if (cboxRoles.getSelectedIndex() == 4) {
            // txtSalario.setText("2000");
        }
    }//GEN-LAST:event_cboxRolesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    public javax.swing.JPanel Panel_Cancelar;
    public javax.swing.JPanel Panel_Editar;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnActualizar_PanelEditar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar_PanelCancelar;
    private javax.swing.JButton btnCancelar_PanelEditar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar_PanelEditar1;
    private javax.swing.JButton btnSalir_PanelCancelar;
    private javax.swing.JComboBox<String> cboxRoles;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    public void bloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                bloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(false);
        component.setFocusable(false);
    }

    public void desbloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                desbloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(true);
    }
}
