/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Empleado.paneles;

import java.awt.Component;
import java.awt.Container;
import java.awt.GridLayout;
import modelo.entity.Empleado;



/**
 *
 * @author FranDev
 */
public class PanelPerfil extends javax.swing.JPanel {

    /**
     * Creates new form PanelPerfil
     */
    public PanelPerfil() {
        initComponents();
        Panel_RegistroEmpleados.setVisible(false);
        bloquearComponnentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Panel_RegistroEmpleados = new javax.swing.JPanel();
        btnAceptarEm = new javax.swing.JButton();
        btnCancelarEm = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtApellidoEdit = new javax.swing.JTextField();
        txtTelefonoEdit = new javax.swing.JTextField();
        txtCorreoEdit = new javax.swing.JTextField();
        txtPasswordEdit = new javax.swing.JTextField();
        txtNombreEdit = new javax.swing.JTextField();
        txtDireccionEdit = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTTelefono = new javax.swing.JTextField();
        TXTNombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TXTApellido = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TXTRol = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TXTPassword = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtUsuarioLoged1 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel25.setText("Correo Electronico");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 27, 118, -1));

        Panel_RegistroEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        Panel_RegistroEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Panel_RegistroEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_RegistroEmpleados.setEnabled(false);
        Panel_RegistroEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarEm.setBackground(new java.awt.Color(102, 204, 0));
        btnAceptarEm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAceptarEm.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarEm.setText("ACEPTAR");
        btnAceptarEm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEmActionPerformed(evt);
            }
        });
        Panel_RegistroEmpleados.add(btnAceptarEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 130, 30));

        btnCancelarEm.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarEm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelarEm.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarEm.setText("CANCELAR");
        btnCancelarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEmActionPerformed(evt);
            }
        });
        Panel_RegistroEmpleados.add(btnCancelarEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 130, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Telefóno");
        Panel_RegistroEmpleados.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 260, 20));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        Panel_RegistroEmpleados.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Contraseña");
        Panel_RegistroEmpleados.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Correo Electronico");
        Panel_RegistroEmpleados.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, -1));

        txtApellidoEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellidoEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoEditActionPerformed(evt);
            }
        });
        txtApellidoEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoEditKeyTyped(evt);
            }
        });
        Panel_RegistroEmpleados.add(txtApellidoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        txtTelefonoEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefonoEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoEditActionPerformed(evt);
            }
        });
        txtTelefonoEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoEditKeyTyped(evt);
            }
        });
        Panel_RegistroEmpleados.add(txtTelefonoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, -1));

        txtCorreoEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCorreoEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEditActionPerformed(evt);
            }
        });
        txtCorreoEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoEditKeyTyped(evt);
            }
        });
        Panel_RegistroEmpleados.add(txtCorreoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 350, -1));

        txtPasswordEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPasswordEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordEditActionPerformed(evt);
            }
        });
        txtPasswordEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordEditKeyTyped(evt);
            }
        });
        Panel_RegistroEmpleados.add(txtPasswordEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 340, 30));

        txtNombreEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombreEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEditActionPerformed(evt);
            }
        });
        txtNombreEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEditKeyTyped(evt);
            }
        });
        Panel_RegistroEmpleados.add(txtNombreEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, -1));

        txtDireccionEdit.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccionEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDireccionEdit.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEditActionPerformed(evt);
            }
        });
        txtDireccionEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionEditKeyTyped(evt);
            }
        });
        Panel_RegistroEmpleados.add(txtDireccionEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 350, -1));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Dirección");
        Panel_RegistroEmpleados.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Editar Datos Personales");
        Panel_RegistroEmpleados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 320, 50));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Apellido");
        Panel_RegistroEmpleados.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, 20));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Nombre");
        Panel_RegistroEmpleados.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        add(Panel_RegistroEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 400, 470));

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Correo Electrónico");
        panelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        TXTCorreo.setBackground(new java.awt.Color(255, 255, 255));
        TXTCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTCorreo.setForeground(new java.awt.Color(0, 0, 0));
        TXTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCorreoActionPerformed(evt);
            }
        });
        panelDatos.add(TXTCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 220, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección");
        panelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        TXTDireccion.setBackground(new java.awt.Color(255, 255, 255));
        TXTDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTDireccion.setForeground(new java.awt.Color(0, 0, 0));
        TXTDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDireccionActionPerformed(evt);
            }
        });
        panelDatos.add(TXTDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 220, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Telefóno");
        panelDatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        TXTTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TXTTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTTelefono.setForeground(new java.awt.Color(0, 0, 0));
        TXTTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTelefonoActionPerformed(evt);
            }
        });
        panelDatos.add(TXTTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 220, -1));

        TXTNombre.setBackground(new java.awt.Color(255, 255, 255));
        TXTNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTNombre.setForeground(new java.awt.Color(0, 0, 0));
        TXTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreActionPerformed(evt);
            }
        });
        panelDatos.add(TXTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 220, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombre");
        panelDatos.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        TXTApellido.setBackground(new java.awt.Color(255, 255, 255));
        TXTApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTApellido.setForeground(new java.awt.Color(0, 0, 0));
        TXTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTApellidoActionPerformed(evt);
            }
        });
        panelDatos.add(TXTApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 220, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Apellido");
        panelDatos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 120, -1));

        TXTRol.setBackground(new java.awt.Color(255, 255, 255));
        TXTRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTRol.setForeground(new java.awt.Color(0, 0, 0));
        TXTRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRolActionPerformed(evt);
            }
        });
        panelDatos.add(TXTRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 220, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rol");
        panelDatos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        TXTPassword.setBackground(new java.awt.Color(255, 255, 255));
        TXTPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXTPassword.setForeground(new java.awt.Color(0, 0, 0));
        TXTPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPasswordActionPerformed(evt);
            }
        });
        panelDatos.add(TXTPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 260, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Contraseña");
        panelDatos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 560, 420));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuarioLoged1.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioLoged1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        txtUsuarioLoged1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioLoged1.setText("Perfil");
        jPanel1.add(txtUsuarioLoged1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 410, 50));

        btnEditarPerfil.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 106, 32));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 560, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        Panel_RegistroEmpleados.setVisible(true);
        bloquear(panelDatos);
        FormEditarPerfil();
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnAceptarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEmActionPerformed
        desbloquear(panelDatos);
        bloquearComponnentes();
        Panel_RegistroEmpleados.setVisible(false);

        //creamos una arreglo de tipos object
        //Object fila[] = new Object[7];
        // ArrayList<String> list = new ArrayList<>();
        //obtenemos los datos que agrega el usuario
        // String tDni = txtDni.getText();
        //String tNombre = txtNombre.getText();
        //String tApellido = txtApellido.getText();
        //  String puesto = (String) cboxPuesto.getSelectedItem();
        //  String tSalario = txtSalario.getText();
        //  String tTelefno = txtTelefono.getText();
        // list.add(tDni); //0
        // list.add(tNombre); //1
        // list.add(tApellido); //2
        //falta fecha de contratacion
        // list.add(puesto); //3
        //  list.add(tSalario);//4
        // list.add(tTelefno);//5
        //  administrador.registrarEmpleado(modTablaEmpleados, list);

        /*
        String tPuesto = String.valueOf(cboxPuesto.getSelectedItem());
        //
        Empleado empledo1 = new Mozo(tDni, tPuesto, 200, tNombre, tApellido, "", tTelefno, "");
        //        administrador.registrarEmpleado(empledo1);
        //"DNI","NOMBRE","APELLIDO","TELEFONO" ,"PUESTO","FECHA INGRESO","SALARIO"
        //agregamos cada ctenido al arreglo
        fila[0] = empledo1.getDni();
        fila[1] = empledo1.getNombre();
        fila[2] = empledo1.getApellido();
        fila[3] = empledo1.getCelular();
        fila[4] = empledo1.getPuesto();
        fila[5] = "200";
        fila[6] = empledo1.getSalario();
        //agregamos una fila  a la tabla con el contedio que tiene el arreglo
        modTablaEmpleados.addRow(fila);
        */
    }//GEN-LAST:event_btnAceptarEmActionPerformed

    private void btnCancelarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEmActionPerformed
        desbloquear(panelDatos);
        bloquearComponnentes();
        Panel_RegistroEmpleados.setVisible(false);
       
    }//GEN-LAST:event_btnCancelarEmActionPerformed

    private void txtApellidoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEditActionPerformed

    private void txtApellidoEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEditKeyTyped

    private void txtTelefonoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoEditActionPerformed

    private void txtTelefonoEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoEditKeyTyped

    private void txtCorreoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEditActionPerformed

    private void txtCorreoEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEditKeyTyped

    private void txtPasswordEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordEditActionPerformed

    private void txtPasswordEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordEditKeyTyped

    private void TXTTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTelefonoActionPerformed

    private void TXTDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDireccionActionPerformed

    private void TXTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCorreoActionPerformed

    private void TXTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreActionPerformed

    private void TXTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTApellidoActionPerformed

    private void TXTRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRolActionPerformed

    private void TXTPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPasswordActionPerformed

    private void txtNombreEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEditActionPerformed

    private void txtNombreEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEditKeyTyped

    private void txtDireccionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEditActionPerformed

    private void txtDireccionEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEditKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_RegistroEmpleados;
    public javax.swing.JTextField TXTApellido;
    public javax.swing.JTextField TXTCorreo;
    public javax.swing.JTextField TXTDireccion;
    public javax.swing.JTextField TXTNombre;
    private javax.swing.JTextField TXTPassword;
    public javax.swing.JTextField TXTRol;
    public javax.swing.JTextField TXTTelefono;
    public javax.swing.JButton btnAceptarEm;
    public javax.swing.JButton btnCancelarEm;
    public javax.swing.JButton btnEditarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDatos;
    public javax.swing.JTextField txtApellidoEdit;
    public javax.swing.JTextField txtCorreoEdit;
    public javax.swing.JTextField txtDireccionEdit;
    public javax.swing.JTextField txtNombreEdit;
    public javax.swing.JTextField txtPasswordEdit;
    public javax.swing.JTextField txtTelefonoEdit;
    public javax.swing.JLabel txtUsuarioLoged1;
    // End of variables declaration//GEN-END:variables

    public void bloquearComponnentes() {
        TXTNombre.setEnabled(false);
        TXTApellido.setEnabled(false);
        TXTCorreo.setEnabled(false);
        TXTTelefono.setEnabled(false);
        TXTDireccion.setEnabled(false);
        TXTRol.setEnabled(false);
        TXTPassword.setEnabled(false);
    }
    
    public void FormEditarPerfil(){
        txtNombreEdit.setText(TXTNombre.getText());
        txtApellidoEdit.setText(TXTApellido.getText());
        txtCorreoEdit.setText(TXTCorreo.getText());
        txtDireccionEdit.setText(TXTDireccion.getText());
        txtTelefonoEdit.setText(TXTTelefono.getText());
        txtPasswordEdit.setText(TXTPassword.getText());
    }
    
    public void limpiarFormEditarPerfil(){
        txtNombreEdit.setText("");
        txtApellidoEdit.setText("");
        txtCorreoEdit.setText("");
        txtDireccionEdit.setText("");
        txtTelefonoEdit.setText("");
    }

    public void bloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                bloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(false);

    }

    public void desbloquear(Component component) {

        if (component instanceof Container) {
            Component[] components = ((Container) component).getComponents();
            for (Component child : components) {
                desbloquear(child); // Llamada recursiva
            }
        }
        component.setEnabled(true);

    }
    
        public Empleado datosUpdateEmpleadoPerfil() {
        Empleado empleadoUpdate = new Empleado();

        empleadoUpdate.setNombre(txtNombreEdit.getText());
        empleadoUpdate.setApellido(txtApellidoEdit.getText());
        empleadoUpdate.setCorreoElectronico(txtCorreoEdit.getText());
        empleadoUpdate.setTelefono(txtTelefonoEdit.getText());
        empleadoUpdate.setDireccion(txtDireccionEdit.getText());
        empleadoUpdate.setPassword(txtPasswordEdit.getText());

     
        return empleadoUpdate;
    }

}
